languageCode = "en-us"
baseurl = "http://rationally.github.io/"
title = "rationally"
theme = "hugo-theme-learn"

[params]
  editURL = "https://github.com/rationally/rationally_hugo/edit/master/content/"
  author = ""
  description = ""
  showVisitedLinks = false