languageCode = "en-us"
baseurl = "http://rationally.github.io/"
title = "rationally"
theme = "hugo-theme-learn"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
canonifyurls: true

[params]
  editURL = ""
  author = ""
  description = ""
  showVisitedLinks = false