languageCode = "en-us"
baseurl = "https://rationally.github.io/"
title = "rationally"
theme = "hugo-theme-learn"
MetaDataFormat = "yaml"
canonifyurls = true

[params]
  editurl = "https://github.com/rationally/rationally_hugo/edit/master/content/"
  author = "University of Groningen"
  description = "Documentation for rationally"
  showVisitedLinks = false